# Output RDS endpoint with port
output "rds-endpoint" {
  value = aws_db_instance.rds.endpoint
}

# eks.tf outputs
output "certificate_authority" { value = aws_eks_cluster.k8squickstart-eks.certificate_authority }

output "eks_id" { value = aws_eks_cluster.k8squickstart-eks.id }

output "eks_endpoint" { value = aws_eks_cluster.k8squickstart-eks.endpoint }

output "eks_ca_data" { value = aws_eks_cluster.k8squickstart-eks.certificate_authority.data }

#--- EKS Outputs ---#
# output "cluster_id" {
#   description = "EKS cluster ID."
#   value       = module.eks.cluster_id
# }

# output "cluster_endpoint" {
#   description = "Endpoint for EKS control plane."
#   value       = module.eks.cluster_endpoint
# }

# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = module.eks.cluster_security_group_id
# }

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }

# output "region" {
#   description = "AWS region"
#   value       = var.aws_region
# }

# output "cluster_name" {
#   description = "Kubernetes Cluster Name"
#   value       = local.cluster_name
# }
